#!/usr/bin/env sh
# vim: set foldmarker={{{,}}} foldlevel=0 foldmethod=marker spell:


# █▓▒░ Maintenance {{{

# quit bspwm normally
super + alt + Escape
	zenity --question --text="Exit WM?" && bspc quit

# make sxhkd reload its configuration files
super + Escape
	pkill -USR1 -x sxhkd

# }}}


# █▓▒░ Non WM {{{

super + Return
	urxvt256c-ml

super + @space
	rofi -show drun

super + alt + d
	mpv --no-terminal --loop --mute "$(xsel)" >> ~/log/sxhkd.log 2>&1

ctrl + shift + c
	catt cast "$(xsel)" >> ~/log/sxhkd.log 2>&1

super + Print
    ~/bin/scregcp -s ~/Pictures/screenshots/

# }}}


# █▓▒░ Window management {{{

# close and kill
super + {_,shift + }w
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + m
	bspc desktop -l next

# if the current node is automatic, send it to the last manual, otherwise pull the last leaf
super + y
	bspc query -N -n focused.automatic && bspc node -n last.!automatic || bspc node last.leaf -n focused

# swap the current node and the biggest node
super + g
	bspc node -s biggest

# set the window state
super + {t,shift + t,f}
	bspc node -t {tiled,pseudo_tiled,fullscreen}

# toggle floating
super + s
	bspc node -t $(bspc query -N -n -n .tiled >/dev/null && echo floating || echo tiled)

# set the node flags
super + ctrl + {x,y,z}
	bspc node -g {locked,sticky,private}

# insert receptacle, or clear receptacles on current desktop
super + {_,shift} + r
    insert={true,false}; \
    $insert && bspc node -i || \
    for win in `bspc query -N -n .leaf.!window`; do bspc node $win -k ; done;

# }}}


# █▓▒░ Setting focus {{{

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop - almost like alt tab
super + {_,shift + }c
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
	bspc {desktop -f,node -d} '^{1-9,10}'

# }}}


# █▓▒░ Preselect direction of new nodes {{{

# preselect the direction of new node
super + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio - the default ratio is 0.5 - pressing 3 makes the old node take up 30%
super + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

# }}}


# █▓▒░ Move and resize {{{

# expand a window by moving one of its side outward
super + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}

# change window gap
super + {minus,equal}
	bspc config -d focused window_gap $((`bspc config -d focused window_gap` {+,-} 2 ))

# }}}
