matches:

  - trigger: ":espanso"
    replace: "Hi theres!"

  - trigger: ":qu"
    replace: "«$|$»"

  - trigger: ":bi"
    replace: "brew install $|$"

  - trigger: ":bu"
    replace: "brew upgrade $|$"

  - trigger: ":gs"
    replace: "git status $|$"

  - trigger: ":gc"
    replace: 'git commit -m "$|$"'

  - trigger: ":ga"
    replace: "git add $|$"

  - trigger: ":gp"
    replace: "git push origin "

  - trigger: ":sig"
    replace: |
      Med vennlig hilsen
      Anders K. Pettersen

  - trigger: ":code"
    replace: |
      ```
      $|$
      ```

  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl 'https://api.ipify.org'"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
