matches:

  - trigger: ":espanso"
    replace: "Hi theres!"

  - trigger: ":qu"
    replace: "«$|$»"

  - trigger: ":sig"
    replace: |
      Med vennlig hilsen
      Anders K. Pettersen

  - trigger: ":ip"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl 'https://api.ipify.org'"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
